" Enable Syntax Highlighting
syntax on

" Enable line numbers
set nu

" Searcing --------------
" Case insensitive search
set ignorecase
set smartcase
set showmatch

" search as characters are entered
set incsearch
" -----------------------

set autoindent 

" Status bar ----------
" Show the status line
set laststatus=2
" Display cursor position
set ruler
set cmdheight=2

" Status line gree on insert, gree on Insert leave
au InsertEnter * hi StatusLine ctermfg=Green
au InsertLeave * hi StatusLine ctermfg=Grey
set statusline=:\ %f%m%r\ %y\ %=[%v,%l]\ [:%L]
" ---------------------

" Switch off flashing and beeping
set visualbell
set t_vb=
set noerrorbells

set confirm
