#!/bin/bash

set eu

ln -fs ~/.cgh/dotfiles/profile ~/.profile
ln -fs ~/.cgh/dotfiles/gitignore ~/.gitignore
ln -fs ~/.cgh/dotfiles/gitconfig ~/.gitconfig
#ln -fs ~/.cgh/dotfiles/rspec ~/.rspec
#ln -fs ~/.cgh/dotfiles/tmux.conf ~/.tmux.conf
